version: "3.5"
services:
  serasa-db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/initdb.sql
      - my-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 330
    networks:
      - default
volumes:
  my-db: